# FROM jenkins/jnlp-agent-node:latest as jnlp
FROM jenkins/inbound-agent:alpine as jnlp

FROM node:16-alpine3.12

# RUN apk -U add openjdk13-jre git 
RUN apk -U add openjdk11-jre git openssh-client
RUN apk update && apk add -u libcurl curl

# Install Docker client
# ARG DOCKER_VERSION=18.03.0-ce
# ARG DOCKER_COMPOSE_VERSION=1.21.0
# RUN curl -fsSL https://download.docker.com/linux/static/stable/`uname -m`/docker-$DOCKER_VERSION.tgz | tar --strip-components=1 -xz -C /usr/local/bin docker/docker
# RUN curl -fsSL https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-`uname -s`-`uname -m` > /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose

COPY --from=jnlp /usr/local/bin/jenkins-agent /usr/local/bin/jenkins-agent
COPY --from=jnlp /usr/share/jenkins/agent.jar /usr/share/jenkins/agent.jar

ENTRYPOINT ["/usr/local/bin/jenkins-agent"]